linters-settings:
  gocyclo:
    min-complexity: 15
  gofmt:
    simplify: true
  misspell:
    locale: US
  govet:
    disable:
      - shadow
    enable-all: true

linters:
  enable:
    - gofmt
    - revive
    - gocyclo
    - misspell
    - govet
    - unused
    - errcheck
    - exportloopref
    - gosimple
    - ineffassign
    - staticcheck
    - testifylint
    - bodyclose
  disable-all: false
  fast: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - .github
  exclude:
    - should have a package comment
    - for error assertions use require
    - should have comment or be unexported
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
