services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=secret
    ports:
      - '127.0.0.1:5432:5432'
    restart: on-failure
networks:
  default:
    name: goyave-backend
